### PR TITLE
26 change backend server to gunicorn

### PR DESCRIPTION
**Pull request by macarious**
# Major changes
Split the original `docker-compose.yml` into 2 versions:
- `docker-compose.dev.yml` contains a development backend server (Flask)
-  `docker-compose.prod.yml` contains a production backend server (Gunicorn).

# Minor changes
- A new directory named `dockerfiles` is created to store the dockerfiles and some configuration files. The `docker-compose` instructions are still intended to be run in the root directory.
- The following files are edited to fix some path dependency issues when running with gunicorn:
   - `/app/init_db`
   - `/app/scripts/db_helper.py`
   - `/log/logger.py`.

# Instructions to build and run the containers
See [DOCKER_REAMD.md](https://github.com/SlangLab-NU/VoiceCollector/blob/26-change-backend-server-to-gunicorn/DOCKER_README.md).

# Server Log
Using `docker-compose.dev.yml`, the server log should state that it is a development server:
```
2023-08-30 10:28:57  * Serving Flask app '__init__.py'
2023-08-30 10:28:57  * Debug mode: off
2023-08-30 10:28:57 Level: INFO
2023-08-30 10:28:57 Time: 2023-08-30 17:28:57,453
2023-08-30 10:28:57 Logger: werkzeug
2023-08-30 10:28:57 Path: _internal:224
2023-08-30 10:28:57 Function :_log
2023-08-30 10:28:57 Message: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
2023-08-30 10:28:57  * Running on all addresses (0.0.0.0)
2023-08-30 10:28:57  * Running on http://127.0.0.1:5000
2023-08-30 10:28:57  * Running on http://172.18.0.4:5000
2023-08-30 10:28:57 
2023-08-30 10:28:57 Level: INFO
2023-08-30 10:28:57 Time: 2023-08-30 17:28:57,454
2023-08-30 10:28:57 Logger: werkzeug
2023-08-30 10:28:57 Path: _internal:224
2023-08-30 10:28:57 Function :_log
2023-08-30 10:28:57 Message: Press CTRL+C to quit
2023-08-30 10:28:57
```

Using `docker-compose.prod.yml`, the server log, when starting, states that it is using gunicorn:
```
2023-08-30 10:31:11 [2023-08-30 17:31:11 +0000] [1] [INFO] Starting gunicorn 20.0.4
2023-08-30 10:31:11 [2023-08-30 17:31:11 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
2023-08-30 10:31:11 [2023-08-30 17:31:11 +0000] [1] [INFO] Using worker: sync
2023-08-30 10:31:11 [2023-08-30 17:31:11 +0000] [7] [INFO] Booting worker with pid: 7
2023-08-30 10:31:11 [2023-08-30 17:31:11 +0000] [8] [INFO] Booting worker with pid: 8
2023-08-30 10:31:11 [2023-08-30 17:31:11 +0000] [9] [INFO] Booting worker with pid: 9
2023-08-30 10:31:11 [2023-08-30 17:31:11 +0000] [10] [INFO] Booting worker with pid: 10
```

### CODE REVIEW

**Review by ztybigcat — COMMENTED** [review]
Everything is working except please move server folder and web folder into dockerfiles folder otherwise those images won't build.

**Comment by macarious** [comment]
> Everything is working except please move server folder and web folder into dockerfiles folder otherwise those images won't build.

I was able to recreate the issue by clearing my cache in my docker app. I have updated the paths in the following files:
- `docker-compose.dev.yml`
- `docker-compose.prod.yml`
- `Dockerfile.web` (to reference the `nginx.default.conf properly`)

The containers should be able to be built and ran now.

**Comment by ztybigcat** [comment]
I misunderstood the behaviour of the app and thought the recording function is still under development thus not working, but after some communication, it seems not be the case.
Upon further testing, I find the recording function is not working unless the server is serving on localhost;
Even when I run the program on localhost (with port forwarding), the app is missing some assets (thomas_birthday?) and the submission function is not working. 
I might be missing something here as I am not familiar with the app and the issue could be totally unrelated to docker, but I suggest we hold off merging until we can figure it out.
Please let me know

**Review by ztybigcat — CHANGES_REQUESTED** [review]
Identified issues potentially related to docker:
API problem when accessed not through localhost.
Another issue with audio submission seems to be unrelated.

**Comment by aanchan** [comment]
Hey @ztybigcat @macarious I think references.txt needs to be reverted to this old version : https://github.com/SlangLab-NU/VoiceCollector/blob/585a11ef2442279cdd4f969734aa9875e2a00992/server/app/references.txt. The one that is on dev I think crept in by error somehow.

**Pull request closed without merging**
